server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          #uri: git@github.com:lgq825994808/spring-cloud-config.git #github仓库上面的git仓库名字
          uri: https://github.com/lgq825994808/spring-cloud-config.git #github仓库上面的git仓库名字
          ##搜索目录
          search-paths:
            - spring-cloud-config
      #读取分支
      label: master

  #rabbit相关配置
  rabbitmq:
    host: 192.168.133.131
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:  #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'  #凡是暴露监控、刷新的都要有actuator依赖，bus-refresh就是actuator的刷新操作