server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        # Nacos服务注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        # sentinel dashboard 地址
        dashboard: localhost:8080
        # 默认为8719，如果被占用会自动+1，直到找到为止
        port: 8719
      # 流控规则持久化到nacos
      datasource:
        dsl:
          nacos:
            server-addr: localhost:8848
            #namespace: 3133f6a5-ebf0-4672-a293-83b9db5520be
            data-id: ${spring.application.name}
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow

service-url:
  nacos-user-service: http://naocs-payment-provider

#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"