server:
  port: 8001
spring:
  application:
    name: cloud-payment-hystrix-service

eureka:
  client:
    register-with-eureka: true    #表示是否将自己注册进EurekaServer默认为true
    fetch-registry: true   #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #defaultZone: http://localhost:7001/eureka  单机配置
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001   #用于在Eureka上显示的项目名称
    prefer-ip-address: true    #访问路径可以显示ip地址
    #自我保护机制配置
    lease-renewal-interval-in-seconds: 1    #eureka客户端向服务端发送心跳的时间间隔（默认是30S）
    lease-expiration-duration-in-seconds: 2  #eureka服务端在接收到最后一次心跳后等待的时间上限，超时将剔除服务，（默认是90秒）
